- magic-string.js
- src/Bundle/index.js
- src/MagicString/index.js
- test/index.js
The way trim() is being used in esperanto is often intended to trim lines only, not other whitespace. This provides an API for doing so.
> Trim lines

- src/MagicString/index.js
- test/index.js
It seems that inserting at the same position multiple times can cause parts of the string to duplicate. The example in this commit is given `ab` and inserting `1` between `a` and `b`, followed by inserting `2` at the same position, yields `a121b` instead of the expected `a21b`.
> Support repeatedly inserting at the same position.

- src/MagicString/index.js
- test/index.js
Without this it’s quite easy to accidentally pass an array, which may
seem to just work but will have the wrong length, causing further
operations at or after the affected location to be wrong.
> Disallow non-string content.

- src/MagicString/index.js
- test/index.js
When inserting at non-zero positions the string is placed after any previous strings that would have been placed at that position. Before this commit, inserting at position 0 was treated specially, deferring to the `prepend` operation. This commit changes the behavior of inserts at 0 to match inserts at any other position. If the old behavior is desired, `prepend` should be called directly.
For context, this is an issue for `decaffeinate` because, given this CoffeeScript:
```coffeescript
a = 1
b = c = 2
```
I would like the final output to be this:
```js
var c;
var a = 1;
var b = c = 2;
```
However, what's actually being output is this:
```js
var var c;
a = 1;
var b = c = 2;
```
decaffeinate inserts `var c;\n` at 0 first because it wants that to be above any other statements. It then …
> Ensure inserting at position 0 is consistent with non-zero positions.

- src/MagicString.js
- test/index.js
This fixes an issue I ran into trying to update [esnext](https://github.com/esnext/esnext) to the latest magic-string.
> Do not overwrite inserts at the end of patched ranges.

- src/MagicString.js
- test/index.js
This fixes a few issues with slice introduced recently. Tests are added which fail before this patch.
* slice now considers `intro` and `outro`: the recent change from `insert` to `insertLeft`/`insertRight` changed implementations to use `intro`/`outro` on a chunk, but slice wasn't updated to this new impl. Now, any `intro`/`outro` contained within the slice bounds is included in the result.
* slice was broken if called after a `removed` or otherwise `edited` chunk: Because all chunks were being considered, regardless of if they overlapped the sliced range, a false-positive error was thrown indicating slicing a removed range. Now chunks which end before the sliced range are quickly skipped, removing the issue. As a bonus this adds a clarification of *which* bound was problematic.
* slice …
> FIX: slice considers intro/outro, no throw after removal

- src/Chunk.js
- src/MagicString.js
- test/index.js
This changes the `overwrite` and `remove` behavior to be consistent with `move`
and `slice`: the specified range includes any `insertRight`s on the left side
and any `insertLeft`s on the right side.
The code change ended up actually making the code simpler: `Chunk.edit` now
overwrites all chunk content, including the intro and outro, so the `overwrite`
code doesn't need to be careful about clearing the intro and outro for specific
chunks.
This fixes https://github.com/decaffeinate/decaffeinate/issues/269 . See my
comment in that bug for an explanation of what was going wrong, and why this
case is important.
In addition to this passing all of the magic-string tests, I also ran all of the
decaffeinate tests with this change and they all pass. So at least with the
decaffeinate project, the …
> Change overwrite and remove to remove interior inserts

- src/Bundle.js
It's optional for MagicString.prototype.generateMap. This seems like a logical symmetry.
> Make options optional for Bundle.prototype.generateMap.

- README.md
- src/Chunk.js
- src/MagicString.js
- test/MagicString.js
> (ap|pre)pend(Left|Right)

- src/MagicString.js
This collapses any obsolete chunks into one following `overwrite` or `remove` – i.e. instead of the edited chunk containing the overwrite followed by N empty chunks, it links the edited chunk directly to the next one. Linked lists FTW
> optimisation - remove empty chunks when overwriting

- index.d.ts
- src/MagicString.js
- test/MagicString.js
This also fixes an issue I discovered while figuring out what type `indentExclusionsRanges` was supposed to be. `MagicString#clone` does not appear to work when the object was constructed with a non-tuple. It seemed to expect an array of nodes – or something with `start` and `end` properties – but generated an array of tuples. Calling `#clone` multiple times no matter what the starting value would have resulted in an incorrect clone. I'm not 100% sure that I picked the right type, but this seemed the most consistent choice.
> Update types to better match reality.

- .eslintrc
- src/MagicString.js
- test/MagicString.js
- test/utils/IntegrityCheckingMagicString.js
Fixes #115
This commit adds a new `IntegrityCheckingMagicString` class that subclasses
`MagicString` and does an integrity check operation, which is used in test code.
This revealed 5 bugs, all of which are also fixed in this commit:
* Within `indent`, the code was calling `chunk.split`, then making an attempt at
properly updating `byStart` and `byEnd`. But it wasn't properly updating
`lastChunk`. Rather than calling `chunk.split`, we can just call
`this._splitChunk`, which updates `byStart`, `byEnd`, and `lastChunk`
correctly.
* `move` could sometimes assign `undefined` as a `next` pointer, which is
inconsistent since all other cases use `null`. Not a really big deal, but nice
to be consistent.
* `overwrite` was attempting to do a linked list removal in a way that wasn't
properly …
> Add integrity checking to tests and fix various bugs

- index.d.ts
`SourceMapOptions` does not include most of `SourceMap`'s keys.
`source` was also missing and added.
In addition, `SourceMap` is now an interface so that TypeScript won't let user code to use it with `new` (it's not being exported from main)
> Correct SourceMap/Options TypeScript definitions

- index.d.ts
As I understand things, the `declare module` TypeScript syntax creates a
globally-importable name and says that any import with that name maps to the
given type. This means it usually works for libraries, but breaks down when
you have multiple versions of the same library loaded, since they each redefine
the same global name. It's really meant for things like Node.js built-in
modules. Instead, `.d.ts` files in libraries should just do exports at the
top-level, and TypeScript allows different versions of the same library to
peacefully coexist in that case.
I ran into a dependency hell problem that I think was caused by this issue where
decaffeinate pulled in three different versions of magic-string that conflicted.
I was able to change the dependency tree so it's just one version, which …
> Don't use `declare module` for TypeScript types

- index.d.ts
This adds missing interfaces used by Rollup in the progress of https://github.com/rollup/rollup/pull/1806.
> Add interfaces used by rollup

- package-lock.json
- package.json
- src/utils/Mappings.js
Removes custom mappings encoding code in favor of the `sourcemap-codec` module (which also just got a faster version). Should make `generateMap` about 20-25% faster. cc @Rich-Harris @alangpierce
> Remove cruft, use sourcemap-codec

- index.d.ts
- src/Bundle.js
- src/MagicString.js
- src/index.js
- src/utils/Mappings.js
- src/utils/SourceMap.js
@Rich-Harris see https://github.com/rollup/rollup/issues/2061 for motivation behind this change. It will make Rollup source map generation almost 2x faster.
- Add `MagicString`/`MagicStringBundle` `generateDecodedMap` method, which returns a JSON representation of a source map (with array-form mappings).
- Expose `SourceMap` class that accepts this form and creates a spec-compliant source map object.
- Add corresponding TypeScript types.
P.S. Feel free to add me as a collaborator — I can triage some open issues/PRs.
> Add generateDecodedMap and expose SourceMap class

- index.d.ts
- src/Bundle.js
- src/MagicString.js
- test/MagicString.js
This supports `bundle.isEmpty()` and `source.isEmpty()` to avoid the need to do a full `bundle.toString().trim().length === 0` check.
Some other minor changes avoid unnecessary internal `toString()` calls.
> isEmpty and other ways to avoid toString() calls

- src/Chunk.js
- test/MagicString.js
This fixes a bug where the intro and outro were being removed on trimmed chunks.
This caused issues where `magicSting.appendRight('x').trim()` would remove the `'x'` part.
> Fix trim bug with intro/outro

- index.d.ts
[`SourceMap.js`](https://github.com/Rich-Harris/magic-string/blob/v0.25.2/src/SourceMap.js#L14) sets `this.version = 3`, but the type definitions claimed that `version` is a string.
My guess is that the type definitions for `magic-string` were based on those of `source-map` version 0.6 (or lower), which [had an incorrect type](https://github.com/mozilla/source-map/blob/0.6.1/source-map.d.ts#L7) for `version`. `source-map` version 0.7 [has the correct type](https://github.com/mozilla/source-map/blob/0.7.3/source-map.d.ts#L16).
> Fix type of SourceMap.version

- src/MagicString.js
- test/MagicString.js
MagicString instances, when cloned would not inherit their intro and outro properties. Add test to ensure that a cloned MagicString with prefix and suffix will produce a generated string matching the original. Correctly clone `.intro` and `.outro` to get the expected behaviour.
Fixes #162.
> Clones intro and outro of MagicString

- src/utils/Mappings.js
- test/MagicString.js
when prepend, the generated map is not recognized by chrome/firefox: can not set break point on second line when there are multiple lines
> fix sourcemap of prepend when hire false

- src/utils/Mappings.js
- test/MagicString.js
Fixes #149
Also fixes two incorrect test results and the rollup issue:
rollup/rollup#3001
> Don't emit source mappings for removed strings.

- index.d.ts
`SourceMapSegment`s aren't really `number[]` types, they're tuples of 1, 4, or 5 numbers.
See the discussion we're having at https://github.com/rollup/rollup/pull/2985#discussion_r300591076
> Export SourceMapSegment tuple types

- src/BitSet.js
- src/MagicString.js
- src/utils/Mappings.js
It was using an object to store positions in the string. This meant that those offsets were first stringified and then added as object properties. For a 200K JS code file (as parsed by rollup), the
`sourcemapLocations` object was taking up 980K. Switching it to a `BitSet` (contribution by @kzc) that uses one bit per offset makes it take up 36K instead.
Fixes #167
> Reduce memory overhead of sourcemapLocations

- src/BitSet.js
Per [this comment](https://github.com/Rich-Harris/magic-string/commit/76487c07b41559884e41607cb48d4158ee26cff9#r36715137) from @Th0rN13. According to my microbenchmarks, this is indeed a (probably very modest!) performance win
> more bitwise trickery

- src/utils/Mappings.js
- test/MagicString.Bundle.js
fixes #172 and https://github.com/rollup/rollup/issues/3001
> fix bundle mappings after remove and move in multiple sources

- index.d.ts
Without this, something like `new MagicString('...', { filename })` is marked as invalid
> fix(types): mark `MagicString` options as optional

- package.json
This is to satisfy TypeScript's `nodenext` behavior
> fix: specify types in exports

- README.md
- src/MagicString.js
- test/MagicString.js
> feat: fix `.replace()` when searching string, add `.replaceAll()`

- benchmark/index.mjs
- src/Chunk.js
As described here https://humanwhocodes.com/blog/2015/11/performance-implication-object-defineproperty/
`Object.defineProperty` does add some overhead.
This can become significant when a lot of splitting is involved.
This PR restrict the usage of `Object.defineProperty` in DEBUG only.
A benchmark using overwrite has been added, an show significant improvement.
other benchmarks have been improved too.
before
```
construct x 78,561 ops/sec ±0.50% (93 runs sampled)
append x 5,732,848 ops/sec ±5.76% (44 runs sampled)
indent x 2,386 ops/sec ±1.50% (89 runs sampled)
generateMap (no edit) x 1,283 ops/sec ±1.86% (89 runs sampled)
generateMap (edit) x 1,346 ops/sec ±0.76% (93 runs sampled)
generateDecodedMap (no edit) x 1,604 ops/sec ±1.07% (92 runs sampled)
generateDecodedMap (edit) x 1,574 …
```
> perf: avoiding use of Object.defineProperty in Chunk constructor

- benchmark/index.mjs
- package-lock.json
- package.json
- rollup.config.js
- src/SourceMap.js
[`@jridgewell/sourcemap-codec` has better performance and memory footprint than `sourcemap-codec`](https://github.com/jridgewell/sourcemap-codec#benchmarks).
This PR replaces `sourcemap-codec` with `@jridgewell/sourcemap-codec`.
**before**
```
node v16.16.0
generateMap (no edit) x 1,664 ops/sec ±0.62% (92 runs sampled)
generateMap (edit) x 1,651 ops/sec ±0.74% (92 runs sampled)
```
**after**
```
node v16.16.0
generateMap (no edit) x 1,981 ops/sec ±0.52% (93 runs sampled)
generateMap (edit) x 1,901 ops/sec ±0.56% (93 runs sampled)
```
> perf: use `@jridgewell/sourcemap-codec`

- package.json
The TypeScript docs say `types` must come first: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
> Put `types` first in `exports`

- index.d.ts
- src/SourceMap.js
- test/MagicString.SourceMap.js
This patch introduces support for the `x_google_ignoreList` field to the `SourceMap` class. This extension was added to the Source Map Revision 3 Proposal[^1] to allow build tools to provide hints to debuggers (e.g. browser DevTools) about which files contain library or framework, and should thus be ignored by default for the purpose of stepping, break on exceptions, and the like[^2].
With this change it's possible for consumers of magic-string's `SourceMap` class to thread through and serialize the newly added `x_google_ignoreList` field (for example this is needed for rollup to support `x_google_ignoreList`).
In a follow up change, we will also add support to the `Bundle` class to mark certain sources as ignore listed.
Ref: https://github.com/Rich-Harris/magic-string/issues/241
[^1]: …
> feat(x_google_ignoreList): initial support for ignore lists

- src/Bundle.js
- src/MagicString.js
This fixes `generateDecodedMap()` to avoid putting `null` into the `sources` array (which is supposed to contain only strings), and also don't assign `null` to the `file` field (which can be either a string or absent - indicated by `undefined`).
> fix: `null` is invalid for `sources` and `file`

- README.md
- index.d.ts
- src/Bundle.js
- src/MagicString.js
- test/MagicString.Bundle.js
- test/MagicString.js
This adds the ability to mark sources emitted into a source map as ignore-listed, which provides a hint that debuggers can utilize when dealing with these sources[^1].
The `ignoreList` option can be passed to a `MagicString` now, and will be considered when generating a source map for it. In addition that bit will also be considered when the `MagicString` is added as source to a `Bundle` (with the possibility to override the value via a parameter to `addSource`). The `x_google_ignoreList` field in the source map will only be emitted if at least one of its sources was explicitly marked with `ignoreList: true`. Otherwise - and primarily for backwards compatibility with the existing ecosystem - no `x_google_ignoreList` field is emitted.
Fixes Rich-Harris/magic-string#241
[^1]: …
> feat: add the ability to ignore-list sources

- .github/workflows/test.yml
We probably only need to run `lint` on a single Node version
Note to self: Node 10 dropped earlier simply because `mocha` doesn't run on Node 10: https://github.com/Rich-Harris/magic-string/pull/204
> chore: add Node 18 to CI

- src/utils/Mappings.js
- test/MagicString.js
fixes #248
I tested out the repro in the issue and it worked with this.
> fix: correct mappings for update containing new line

- src/index.d.ts
The `sourcesContent` has been changed in #242, and will longer return null, but it may be `undefined`.
> fix: update `sourcesContent` type

- src/Chunk.js
- src/MagicString.js
- src/index.d.ts
- test/MagicString.js
The `MagicString.reset` method resets chars in the specified range to its original version.
The `Chunk.resetToOriginal` method resets the chunk to its original version. (empty `intro` and `outro`, and set `edited` to `false`)
1. Restore previously removed range (#218)
2. Discard unwanted changes
> I don't know much about sourcemap, so I'm not 100% sure that the sourcemap produced by this method is correct.
> feat: new `reset` method (#218)

- README.md
I am so sorry. Because of my carelessness, I forgot to add the new `reset` method (introduced in #271) to the README.
> docs: add `reset` method to README

- src/utils/Mappings.js
- test/MagicString.js
When the string passed to update or overwrite ends with a new line, the mappings will contain two entries for column zero. This happens because the loop does not bail if the last line is empty, filling two lines with the same mapping. This commit fixes that. Fixes #273
> fix: handle last empty line correctly when using update/overwrite

- benchmark/data.js
- src/MagicString.js
- test/MagicString.js
> fix: not use negative indices for remove in empty string

- src/utils/Mappings.js
- test/MagicString.js
This PR removes line break mappings from the output sourcemap and reduces the output sourcemap.
[visualizer before](https://evanw.github.io/source-map-visualization/#NDI2AGZ1bmN0aW9uIGZvbygpew0KICBjb25zb2xlLmxvZygiYmFyIikNCn0NCi8vIyBzb3VyY2VNYXBwaW5nVVJMPWRhdGE6YXBwbGljYXRpb24vanNvbjtjaGFyc2V0PXV0Zi04O2Jhc2U2NCxleUoyWlhKemFXOXVJam96TENKbWFXeGxJam9pYjNWMGNIVjBMbXB6SWl3aWMyOTFjbU5sY3lJNld5SnBibkIxZEM1cWN5SmRMQ0p6YjNWeVkyVnpRMjl1ZEdWdWRDSTZXeUptZFc1amRHbHZiaUJtYjI4b0tYdGNiaUFnWTI5dWMyOXNaUzVzYjJjb1hDSmlZWEpjSWlsY2JuMGlYU3dpYm1GdFpYTWlPbHRkTENKdFlYQndhVzVuY3lJNklrRkJRVUVzVVVGQlVTeERRVUZETEVkQlFVY3NRMEZCUXl4RFFVRkRMRU5CUVVNN1FVRkRaaXhEUVVGRExFTkJRVU1zVDBGQlR5eERRVUZETEVkQlFVY3NRMEZCUXl4RFFVRkRMRWRCUVVjc1EwRkJReXhEUVVGRE8wRkJRM0JDSW4wPTIzOQB7InZlcnNpb24iOjMsImZpbGUiOiJvdXRwdXQuanMiLCJzb3VyY2VzIj …
> perf: skip line break mappings

- src/index.d.ts
> chore: fix move jsdoc typo

- src/SourceMap.js
Debug IDs are unique uuids added to both source and sourcemaps so sourcemaps can more easily be identified in production. See the [TC39 proposal](https://github.com/tc39/source-map/blob/main/proposals/debug-id.md) for more details
I've recently added support for emitting debug IDs in [Rollup](https://rollupjs.org/configuration-options/#output-sourcemapdebugids), webpack and Rolldown.
Even though this has been released in Rollup, it doesn't work In Vite yet because the debug ID gets removed from every sourcemap when a later plugin makes modifications to the sourcemap. I think I've tracked this down to `magic-string`!
> feat: Add support for sourcemap `debugId` property

- src/index.d.ts
Sorry, in #292 I failed to update the `SourceMap` type to include the new property!
> feat: Include `debugId` in `SourceMap` types

- package.json
Add side effects to package.json, help bundlers cut unused code with treeshake. Good for esm, modules, named imports.
> feat: add `sideEffects: false` to package.json

- src/utils/Mappings.js
- test/MagicString.test.js
In some cases, a mapping was missing after a line break with `hires: 'boundary'`.
[Example output](https://evanw.github.io/source-map-visualization/#MjgALy8gZm9vCmNvbnNvbGUubG9nKCJoZWxsbyIpCjE4NQB7InZlcnNpb24iOjMsImZpbGUiOiJvdXRwdXQuanMiLCJzb3VyY2VzIjpbImlucHV0LmpzIl0sInNvdXJjZXNDb250ZW50IjpbIi8vIGZvb1xuY29uc29sZS5sb2coXCJiYXJcIikiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsQ0FBQyxDQUFDLENBQUM7T0FDSSxDQUFDLEdBQUcsQ0FBQyxDQUFDLEtBQUcsQ0FBQyJ9Cg==)
This PR fixes that. [Example new output](https://evanw.github.io/source-map-visualization/#MjgALy8gZm9vCmNvbnNvbGUubG9nKCJoZWxsbyIpCjE5MAB7InZlcnNpb24iOjMsImZpbGUiOiJvdXRwdXQuanMiLCJzb3VyY2VzIjpbImlucHV0LmpzIl0sInNvdXJjZXNDb250ZW50IjpbIi8vIGZvb1xuY29uc29sZS5sb2coXCJiYXJcIikiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsQ0FBQyxDQUFDLENBQUM7QUFDSCxPQUFPLENBQU …
> fix: missing mapping after a line break with `hires: 'boundary'`

- src/MagicString.js
- test/MagicString.test.js
I guess there are many different ways to solve this. So I'm open for other solutions.
> fix: prevent infinite loop on empty input

- src/MagicString.js
- test/MagicString.test.js
> feat: `replace(All)` support replacement for functions when the first parameter is a string
